@extends('pages.policy6')
@section('policiescontent')

<div class="group-content">
                          <div class="bai-viet-detail">
                <h1 class="title">Chính sách giải quyết tranh chấp</h1>
        <div class="social-item">
            <div class="fb-like" data-href="http://thuongdo.com//chinh-sach-giai-quyet-tranh-chap" data-width="100" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
            <div class="g-plusone" data-size="medium"></div>
        </div>
                                                    <div class="noi-dung"><p><strong>I.Tiếp nhận khiếu nại:</strong><br />  Thương đô sẽ tiếp nhận mọi khiếu nại và hỗ trợ khách hàng một cách tối đa liên quan đến giao dịch tại website:&nbsp;thuongdo.com Khi phát sinh tranh chấp, Thương đô đề cao giải pháp thương lượng, hòa giải giữa các bên nhằm duy trì sự tin cậy của&nbsp;khách hàng&nbsp;vào chất lượng dịch vụ của Thương đô và thực hiện quy trình xử lý khiếu nại.<br />  Cách thức liên hệ: Khách hàng gửi khiếu nại liên quan đến giao dịch thực hiện trên website bằng cách liên hệ với Thương đô thông qua một trong các hình thức sau đây:</p>    <p><br />  <strong>1. Gọi điện thoại: 1900 6825&nbsp;&nbsp;<br />  2. Gửi email: chamsoc@thuongdo.com<br />  3. Gửi văn bản hoặc gặp trực tiếp đến địa chỉ làm việc:<br />  3.1.&nbsp;Địa chỉ trụ sở chính: </strong>Số nhà 9, ngõ 7 đường Lê Đức Thọ, Phường Mỹ Đình 2, Quận<br />  Nam Từ Liêm, Thành phố Hà Nội, Việt Nam<br />  <strong>3.2. Văn phòng kinh doanh miền bắc:</strong><br />  - 14 Nguyễn Viết Xuân, phường Khương Mai, quận Thanh Xuân, T.P Hà Nội.<br />  - 335 Ngô Gia Tự , phường Cát Bi, quận Hải An, T.P Hải Phòng.<br />  <strong>3.3. Văn phòng kinh doanh miền nam: </strong>911 Nguyễn Trãi, phường 02, quận 5, T.P Hồ Chí<br />  Minh.<br />  <strong>&nbsp;<br />  II.&nbsp;Trách nhiệm giải quyết khiếu nại:</strong><br />  Khiếu nại liên quan đến dịch vụ của Công ty trên website thuongdo.com: Như &nbsp;khiếu nại về thông tin đăng tải, Khiếu nại về chính sách bảo mật thông tin,… Đối với những khiếu nại này, Thương Đô sẽ chịu trách nhiệm giải quyết cho người khiếu nại trong vòng 24 giờ kể từ thời điểm nhận được thông tin khiếu nại. Thương đô là đơn vị giao nhận, vận chuyển hàng hóa, do vậy Thương Đô không chịu trách nhiệm giải quyết khiếu nại cho<br />  Khách hàng liên quan đến thông tin, đặc điểm hàng hóa, dịch vụ. Tuy nhiên, Thương Đô có vai trò hỗ trợ khách hàng liên hệ với Nhà sản xuất/Đơn vị cung cấp để yêu cầu giải quyết khiếu nại và các hỗ trợ khác trong khả năng để giúp Khách hàng bảo vệ quyền lợi hợp pháp của mình.</p>    <p><br />  <strong>Nếu cần hỗ trợ, hãy gọi theo số&nbsp;1900 6825<br />  Hoặc email: chamsoc@thuongdo.com</strong></p></div>
                            <div class="tin-lien-quan block">
                <h3>Tin liên quan</h3>
                <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-va-quy-dinh-chung" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-va-quy-dinh-chung" class="title" title="Chính sách và quy định chung">Chính sách và quy định chung</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-doi-tra-va-hoan-tien" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-doi-tra-va-hoan-tien" class="title" title="Chính sách đổi trả và hoàn tiền">Chính sách đổi trả và hoàn tiền</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-bao-mat-thong-tin-ca-nhan" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-bao-mat-thong-tin-ca-nhan" class="title" title="Chính sách bảo mật thông tin cá nhân">Chính sách bảo mật thông tin cá nhân</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 last" style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-bao-hanh" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-bao-hanh" class="title" title="Chính sách bảo hành">Chính sách bảo hành</a></div></div></div></div>            </div>
            </div>
                </div>
@endsection