@extends('pages.policy6')
@section('policiescontent')

<div class="group-content">
                          <div class="bai-viet-detail">
                <h1 class="title">Chính sách bảo hành</h1>
        <div class="social-item">
            <div class="fb-like" data-href="http://thuongdo.com//chinh-sach-bao-hanh" data-width="100" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
            <div class="g-plusone" data-size="medium"></div>
        </div>
                                                    <div class="noi-dung"><p><strong>1. </strong>Trong trường hợp mất hàng, nếu bạn không sử dụng dịch vụ bảo hiểm hàng hóa của Thương Đô chúng tôi chỉ bồi thường cho Quý khách gấp 3 lần số tiền vận chuyển.<br />  &nbsp;</p>    <p><strong>2. </strong>Trong trường hợp mất hàng trong quá trình vận chuyển, nếu bạn sử dụng dịch vụ bảo hiểm hàng hóa của Thương Đô (=5% giá trị hàng hóa bạn kê khai) Thương Đô sẽ bồi thường 50% giá trị kiện hàng bạn đã kê khai.<br />  &nbsp;</p>    <p><strong>3. </strong>Chính sách bảo hành đối với từng sản phẩm/hàng hóa/dịch vụ sẽ do Nhà sản xuất/Đơn vị phân phối quy định. Thương đô sẽ hỗ trợ khách hàng liên hệ với Nhà sản xuất/Đơn vị phân phối để giải quyết bảo hành.</p>    <p><strong>Thương Đô.</strong></p></div>
                            <div class="tin-lien-quan block">
                <h3>Tin liên quan</h3>
                <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-va-quy-dinh-chung" class="image img-responsive"><img src="public/frontend/images/htkklogo.png" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-va-quy-dinh-chung" class="title" title="Chính sách và quy định chung">Chính sách và quy định chung</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-doi-tra-va-hoan-tien" class="image img-responsive"><img src="public/frontend/images/htkklogo.png" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-doi-tra-va-hoan-tien" class="title" title="Chính sách đổi trả và hoàn tiền">Chính sách đổi trả và hoàn tiền</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-bao-mat-thong-tin-ca-nhan" class="image img-responsive"><img src="public/frontend/images/htkklogo.png" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-bao-mat-thong-tin-ca-nhan" class="title" title="Chính sách bảo mật thông tin cá nhân">Chính sách bảo mật thông tin cá nhân</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 last" style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-giai-quyet-tranh-chap" class="image img-responsive"><img src="public/frontend/images/htkklogo.png" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-giai-quyet-tranh-chap" class="title" title="Chính sách giải quyết tranh chấp">Chính sách giải quyết tranh chấp</a></div></div></div></div>            </div>
            </div>
                </div>
@endsection