@extends('pages.policy6')
@section('policiescontent')

<div class="group-content">
                          <div class="bai-viet-detail">
                <h1 class="title">Chính sách đổi trả và hoàn tiền</h1>
        <div class="social-item">
            <div class="fb-like" data-href="http://thuongdo.com//chinh-sach-doi-tra-va-hoan-tien" data-width="100" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
            <div class="g-plusone" data-size="medium"></div>
        </div>
                                                    <div class="noi-dung"><p>Thương đô là đơn vị cung cấp dịch vụ giao nhận hàng hóa, việc đổi/trả hàng hóa và hoàn tiền sẽ phụ thuộc và chính sách của từng Nhà sản xuất/Đơn vị cung cấp. Tuy nhiên, Thương Đô sẽ hỗ trợ khách hàng liên hệ với Nhà sản xuất/Đơn vị đại lý để yêu cầu thực hiện đổi/trả hàng và yêu cầu hoàn tiền theo đúng quy định.</p>    <p><strong>Thương Đô.</strong></p></div>
                            <div class="tin-lien-quan block">
                <h3>Tin liên quan</h3>
                <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-va-quy-dinh-chung" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-va-quy-dinh-chung" class="title" title="Chính sách và quy định chung">Chính sách và quy định chung</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-bao-mat-thong-tin-ca-nhan" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-bao-mat-thong-tin-ca-nhan" class="title" title="Chính sách bảo mật thông tin cá nhân">Chính sách bảo mật thông tin cá nhân</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 " style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-giai-quyet-tranh-chap" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-giai-quyet-tranh-chap" class="title" title="Chính sách giải quyết tranh chấp">Chính sách giải quyết tranh chấp</a></div></div></div><div class="uk-width-1-1 uk-width-medium-1-2 last" style="margin-bottom: 10px;"> <div class="uk-grid uk-grid-small"><div class="uk-width-1-1 uk-width-medium-1-3"><a href="/chinh-sach-bao-hanh" class="image img-responsive"><img src="/sites/default/files/default_images/logo_jpg.jpg" width="200" alt="Đặt hàng Trung Quốc" title="Đặt hàng Trung Quốc" /></a></div><div class="uk-width-1-1 uk-width-medium-2-3"><a href="/chinh-sach-bao-hanh" class="title" title="Chính sách bảo hành">Chính sách bảo hành</a></div></div></div></div>            </div>
            </div>
                </div>
@endsection